### ISSUE TITLE
Build frameworks with bitcode

### ISSUE THREAD

**Issue by PilchardFriendly** [NAXAM/braintree-ios-binding#1]
Using 4.8.2.5, we just had our app rejected from the App Store.

We will resubmit with bitcode disabled as a workaround.

This is an issue that the cardio xamarin wrapper also faced.  

See https://github.com/card-io/card.io-iOS-SDK/issues/205

**Comment by tuyen-vuduc** [comment]
Could you plz provide reject reason from Apple?

**Comment by tuyen-vuduc** [comment]
Hey,

I just published latest version of Braintree iOS with bitcode disabled.

Plz check it out if it works well.

Cheers.
