### ISSUE TITLE
iOS / Version 4.9.0 -- missing dependencies

### ISSUE THREAD

**Issue by hschmied** [NAXAM/braintree-ios-binding#3]
Some packages can't be updated to the latest 4.9.0 version, due to a dependency.

`Unable to resolve dependencies. 'Naxam.PayPal.Risk.iOS 4.8.2' is not compatible with 'Naxam.PayPalDataCollector.iOS 4.9.0 constraint: Naxam.PayPal.Risk.iOS (>= 4.9.0)'.
`

I checked in the package manager and the only/latest version available for Naxam.Paypal.Risk.iOS is 4.8.2.

Affected packages seem to be...

.Naxam.BraintreePayPal.iOS
.Naxam.PayPalDataCollector.iOS
.Naxam.PayPalOneTouch.iOS

Thank you!

**Comment by JohannesGESchmidt** [comment]
Please don't let this great project die. this needs to be updated.

**Comment by tuyen-vuduc** [comment]
Pull requests are always welcome, @JohannesSchmidt42. It really takes time to keep the library update-to-date.

**Comment by tuyen-vuduc** [comment]
Plz check the latest version if it's ok now.

84604544cab088599cc6cb7cc8cbe6218703f967

**Comment by tuyen-vuduc** [comment]
Commit 84604544cab088599cc6cb7cc8cbe6218703f967
