### ISSUE TITLE
Paypal option not showing up on DropIn UI for iOS

### ISSUE THREAD

**Issue by rduverna** [NAXAM/braintree-ios-binding#4]
Hi, 

I am trying to implement the DropIn UI in my Xamarin app and it works perfectly for Android.  Both the credit card and PayPal button shows up in the DropIn  UI. However I am struggling with getting the PayPal button to show up for iOS.  So I followed all the steps for iOS to activate PayPal, but can’t seem to get this to work.

I included the following packages in my project:

Naxam.BraintreeCard.iOS
Naxam.BrainTreeCore.iOS
Naxam.BraintreeDataCollector.iOS
Naxam.BraintreeDropIn.iOS
Naxam.BraintreePaymentFlow.iOS
Naxam.BraintreePayPal.iOS
Naxam.BraintreeUI.iOS
Naxam.PayPal.Risk.iOS
Naxam.PayPalDataCollector.iOS
Naxam.PayPalOneTouch.iOS
Naxam.PayPalUtils.iOS

I add the new URL Type inside my AppDelegate.
BraintreeCore.BTAppSwitch.SetReturnURLScheme(“com.app.name.payments");

I add the App Switch handlers in my application delegate to handle the callback URL.  

Please help me figure out what I could possibly be missing.

Thanks

**Comment by tuyen-vuduc** [comment]
Would you mind checking latest package?
